{"name": "Получение несуществующего мема (ожидается 404)", "status": "passed", "attachments": [{"name": "log", "source": "03224f4c-9822-4f43-9e6b-c082a9189025-attachment.txt", "type": "text/plain"}], "start": 1753632198125, "stop": 1753632198300, "uuid": "e7141424-b6a7-4159-93f3-e8704d9b3fd6", "historyId": "b5a2a0045fb81dd09dcb3ce20095dca7", "testCaseId": "b5a2a0045fb81dd09dcb3ce20095dca7", "fullName": "tests.test_negative#test_get_nonexistent_meme", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Negative Tests"}, {"name": "tag", "value": "negative"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_negative"}, {"name": "host", "value": "DESKTOP-RDLQM76"}, {"name": "thread", "value": "8472-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_negative"}]}